name: Terraform

on:
  push:
    branches:
      - main

env:
  GLOBAL_VAR: 'GlobalValue'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'JobSpecificValue'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Check Terraform format
      env:
        STEP_VAR: 'StepSpecificValue'
      run: echo $STEP_VAR

    - name: Set output
       echo "channel=$(echo $CHANNEL)" >> $GITHUB_OUTPUT

    - name: Terraform Plan
      run: terraform plan
